dependencies:
  mqtt:
    url: github.com/toitware/mqtt
    version: ^2.0.3
  ntp:
    url: github.com/toitlang/pkg-ntp
    version: ^1.0.0
  scd30:
    url: github.com/qvisten999/scd30
    version: ^1.0.1
